import Foundation
import SQLite3

/// Fetches transcripts Apple has generated by consulting the local Apple Podcasts library and
/// its TTML cache on macOS (PRD-FEAT-003).
///
/// Apple exposes no public transcript API, so this reads the Podcasts app's own on-disk data and
/// is treated as a fragile, swappable integration (PRD-SEC-009):
///  1. `MTLibrary.sqlite` maps an episode's store id → a transcript *identifier* (a path under the
///     TTML cache). This exists for every episode Apple has a transcript for.
///  2. The TTML file itself is only present once the Podcasts app has downloaded it (i.e. after the
///     user has viewed the transcript). If the identifier exists but the file doesn't, we report
///     `.notDownloaded` so the UI can guide the user, rather than a misleading "not found".
struct AppleTranscriptProvider: TranscriptProvider {
    /// The Apple Podcasts group container, overridable for tests.
    var groupContainer: URL?

    init(groupContainer: URL? = nil) {
        self.groupContainer = groupContainer ?? AppleTranscriptProvider.defaultGroupContainer()
    }

    static func defaultGroupContainer() -> URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Group Containers/243LU875E5.groups.com.apple.podcasts", isDirectory: true)
    }

    private var libraryDatabaseURL: URL? {
        groupContainer?.appendingPathComponent("Documents/MTLibrary.sqlite")
    }

    private var ttmlCacheDirectory: URL? {
        groupContainer?.appendingPathComponent("Library/Cache/Assets/TTML", isDirectory: true)
    }

    func fetchTranscript(for episode: Episode, link: ApplePodcastsLink?) async throws -> FetchedTranscript {
        let episodeID = episode.appleEpisodeID ?? link?.episodeID

        // 1) Preferred path: resolve the exact TTML file via Apple's library database.
        if let episodeID,
           let dbURL = libraryDatabaseURL, FileManager.default.fileExists(atPath: dbURL.path),
           let ttmlDir = ttmlCacheDirectory,
           let identifier = AppleLibraryDatabase.transcriptIdentifier(episodeID: episodeID, databaseURL: dbURL) {
            // On-disk file is "<identifier>-<episodeID>.ttml".
            let file = ttmlDir.appendingPathComponent("\(identifier)-\(episodeID).ttml")
            if FileManager.default.fileExists(atPath: file.path) {
                let xml = try String(contentsOf: file, encoding: .utf8)
                return try TTMLParser.parse(xml)
            }
            // Apple knows a transcript exists, but it isn't cached locally yet.
            throw TranscriptFetchError.notDownloaded
        }

        // 2) Fallback: scan the TTML cache for a file whose name contains the episode id.
        if let file = locateTranscriptFileByScan(episodeID: episodeID) {
            let xml = try String(contentsOf: file, encoding: .utf8)
            return try TTMLParser.parse(xml)
        }

        throw TranscriptFetchError.notFound
    }

    /// Fallback filesystem walk over the TTML cache, bounded so it can't hang.
    private func locateTranscriptFileByScan(episodeID: String?) -> URL? {
        guard let root = ttmlCacheDirectory, FileManager.default.fileExists(atPath: root.path) else { return nil }
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(
            at: root, includingPropertiesForKeys: [.contentModificationDateKey], options: [.skipsHiddenFiles]
        ) else { return nil }

        var newestMatch: (url: URL, date: Date)?
        var scanned = 0
        for case let url as URL in enumerator {
            scanned += 1
            if scanned > 40_000 || Task.isCancelled { break }
            guard url.pathExtension.lowercased() == "ttml" else { continue }
            if let episodeID, !url.lastPathComponent.contains(episodeID) { continue }
            let date = (try? url.resourceValues(forKeys: [.contentModificationDateKey]))?
                .contentModificationDate ?? .distantPast
            if newestMatch == nil || date > newestMatch!.date { newestMatch = (url, date) }
        }
        return newestMatch?.url
    }
}

/// Minimal read-only reader for Apple Podcasts' `MTLibrary.sqlite`. Opens the database as
/// immutable so it never contends with the running Podcasts app.
enum AppleLibraryDatabase {
    static func transcriptIdentifier(episodeID: String, databaseURL: URL) -> String? {
        var db: OpaquePointer?
        // `immutable=1` reads a stable snapshot without taking locks (safe while Podcasts runs).
        // absoluteString gives a correctly percent-encoded file URI (the path has spaces).
        let uri = databaseURL.absoluteString + "?immutable=1"
        guard sqlite3_open_v2(uri, &db, SQLITE_OPEN_READONLY | SQLITE_OPEN_URI, nil) == SQLITE_OK else {
            sqlite3_close_v2(db)
            return nil
        }
        defer { sqlite3_close_v2(db) }

        let sql = """
        SELECT COALESCE(ZTRANSCRIPTIDENTIFIER, ZFREETRANSCRIPTIDENTIFIER, ZENTITLEDTRANSCRIPTIDENTIFIER)
        FROM ZMTEPISODE WHERE ZSTORETRACKID = ? LIMIT 1;
        """
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else { return nil }
        defer { sqlite3_finalize(stmt) }

        // ZSTORETRACKID is numeric; bind as int64 when possible.
        if let value = Int64(episodeID) {
            sqlite3_bind_int64(stmt, 1, value)
        } else {
            sqlite3_bind_text(stmt, 1, episodeID, -1, nil)
        }

        guard sqlite3_step(stmt) == SQLITE_ROW, let c = sqlite3_column_text(stmt, 0) else { return nil }
        let identifier = String(cString: c)
        return identifier.isEmpty ? nil : identifier
    }
}
