import Foundation

/// Fetches transcripts Apple has already generated by locating the local TTML cache that the
/// Podcasts app writes on macOS, then parsing it (PRD-FEAT-003).
///
/// Apple exposes no guaranteed public transcript API, so this is deliberately a *local cache*
/// reader and is treated as a fragile, swappable integration (PRD-SEC-009). When nothing is
/// found it fails cleanly with `.notFound` so the UI can offer a retry (PRD-FEAT-003 acceptance).
struct AppleTranscriptProvider: TranscriptProvider {

    /// Directories that may hold cached transcript TTML files. Overridable for tests.
    var candidateDirectories: [URL]

    init(candidateDirectories: [URL]? = nil) {
        self.candidateDirectories = candidateDirectories ?? AppleTranscriptProvider.defaultCacheDirectories()
    }

    /// Best-effort known locations for the Apple Podcasts transcript cache.
    static func defaultCacheDirectories() -> [URL] {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let groupContainers = home
            .appendingPathComponent("Library/Group Containers", isDirectory: true)
        let caches = home
            .appendingPathComponent("Library/Caches/com.apple.podcasts", isDirectory: true)
        return [groupContainers, caches]
    }

    func fetchTranscript(for episode: Episode, link: ApplePodcastsLink?) async throws -> FetchedTranscript {
        guard let file = locateTranscriptFile(episodeID: episode.appleEpisodeID ?? link?.episodeID) else {
            throw TranscriptFetchError.notFound
        }
        let xml = try String(contentsOf: file, encoding: .utf8)
        return try TTMLParser.parse(xml)
    }

    /// Walks the candidate directories for a `.ttml` file whose name references the episode id.
    /// Falls back to the newest `.ttml` in a folder that clearly matches the episode.
    private func locateTranscriptFile(episodeID: String?) -> URL? {
        let fm = FileManager.default
        for root in candidateDirectories {
            guard let enumerator = fm.enumerator(
                at: root, includingPropertiesForKeys: [.contentModificationDateKey],
                options: [.skipsHiddenFiles]
            ) else { continue }

            var newestMatch: (url: URL, date: Date)?
            for case let url as URL in enumerator where url.pathExtension.lowercased() == "ttml" {
                let name = url.lastPathComponent
                let matches: Bool
                if let episodeID { matches = name.contains(episodeID) } else { matches = true }
                guard matches else { continue }
                let date = (try? url.resourceValues(forKeys: [.contentModificationDateKey]))?
                    .contentModificationDate ?? .distantPast
                if newestMatch == nil || date > newestMatch!.date {
                    newestMatch = (url, date)
                }
            }
            if let hit = newestMatch { return hit.url }
        }
        return nil
    }
}
